#%RAML 1.0 Library

# Name: dd-response-types.raml
#
# Version: 2.0.1
#
# Date: 2018-07-10
#
#  This file defines the response layouts used by /dd API.

uses:
  DD-T: dd-base-types.raml
  GENERIC-RESP: generic-response-types.raml

types:
# response types
#
#  The repsonse layouts are of Location object are similar to DD API 1.9 definition except that not all atttributes that are returned,
#  and DD-strict has additional location properties that are not par of the DD API 1.9 specification.

  AspectSetListResponse:
    description: The list of available AspectSets.
    type: GENERIC-RESP.BaseResponseListHeader
    properties:
      results:
        type: DD-T.AspectSet[]
        description: List of AspectSets.

  LocationListResponseGeoJSON:
    description: Returns the locations as a GeoJson (FeatureCollection)[https://tools.ietf.org/html/rfc7946#page-12].
    type: object

  LocationListResponse:
    description: Contains zero or more responses to a Location list request.
    type: GENERIC-RESP.BaseResponseListHeader
    properties:
      results:
        type: DD-T.Location[]
        description: List of Location objects

  LocationResponse:
    description: Contains the response for one Location.
    type: DD-T.Location
    properties:
      provider?:
        type: DD-T.Provider
        description: The system that generated the response.

  NodeListResponse:
    description: Contains zero or more responses to a Node list request.
    type: GENERIC-RESP.BaseResponseListHeader
    properties:
      results:
        type: DD-T.Node[]
        description: List of Node objects

  NodeResponse:
    description: Contains the response for one Node.
    type: DD-T.Node
    properties:
      provider?:
        type: DD-T.Provider
        description: The system that generated the response.

  ObservationTypeListResponse:
    description:
    type: GENERIC-RESP.BaseResponseListHeader
    properties:
      results:
        type: DD-T.ObservationType[]
        description: List of ObservationType objects

  ObservationTypeResponse:
    description: Contains the response for one ObservationType.
    type: DD-T.ObservationType
    properties:
      provider?:
        type: DD-T.Provider
        description: The system that generated the response.

  SourceListResponse:
    description: Contains zero or more responses to a Source list request.
    type: GENERIC-RESP.BaseResponseListHeader
    properties:
      results:
        type: DD-T.Source[]
        description: List of Datasource.

  TimeseriesListResponse:
    description:
    type: GENERIC-RESP.BaseResponseListHeader
    properties:
      results:
        type: DD-T.Timeseries[]
        description: List of Timeseries objects

  TimeseriesResponse:
    description: Contains the response for one Timeseries.
    type: DD-T.Timeseries
    properties:
      provider?:
        type: DD-T.Provider
        description: The system that generated the response.
