#%RAML 1.0 Library

# Name: ddoper-base-types.raml
#
# Version: 2.0.1
#
# Date: 2019-01-14
#
#  This file defines specific datatypes only used in the DD-OPER API, and/or extends base datatypes of the DD-API.

uses:
  DD-T: dd-base-types.raml

types:

  LocationName:
    type: DD-T.LocationName
