#%RAML 1.0 Library

# Name: generic-response-types.raml
#
# Version: 2.0.1
#
# Date: 2018-07-10
#
#  This file defines the response layouts used by /dd and /dd-oper API.

uses:
  DD-T: dd-base-types.raml

types:
# response types
#
#  The repsonse layouts are of Location object are similar to DD API 1.9 definition except that not all atttributes that are returned,
#  and DD-strict has additional location properties that are not par of the DD API 1.9 specification.

  BaseResponseHeader:
    description: The standard header used in /dd and /dd-oper API for a single object.
    type: object
    properties:
      provider?:
        type: DD-T.Provider

  BaseResponseListHeader:
    description: The standard header used in /dd and /dd-oper API for a multiple objects (lists) with support for paging links.
    type: BaseResponseHeader
    properties:
      paging?:
        type: DD-T.PageLinks

  ErrorResponse:
    description: |
      The standard error header returned in case of an error/problem (when HTTP return code is not 200). The header is in
      line with RFC7807 and can be extended with additional attributes in Error object.
    type: DD-T.Error
    properties:
      provider?:
        type: DD-T.Provider
