#%RAML 1.0 Library

# Name: ddoper-base-types.raml
#
# Version: 2.0.1.1
#
# Date: 2021-07-11
#
#  This file defines specific datatypes only used in the DD-OPER API, and/or extends base datatypes of the DD-API.
#  As most datatypes are now identical the file can be made onsolete. However to allow deviation again in the future or in extended versions of DD_OPER
#  the file is retained. There must be at least one datatype defined to prevent errors. 

uses:
  DD-T: ../../libraries/dd-base-types.raml

types:

  LocationName:
    type: DD-T.LocationName
